import 'package:flutter/material.dart';
import '../../config/constants.dart';
import '../../models/guida.dart';

class GuideData {
  static List<Guida> getAllGuide() {
    return [
      Guida(
        id: 1,
        title: 'Permesso di Soggiorno - Primo Rilascio',
        shortDescription: 'Come ottenere il primo permesso di soggiorno in Italia',
        icon: Icons.badge,
        color: AppColors.iconBlue,
        category: 'Permesso',
        tempiStimati: '60-90 giorni',
        costoStimato: '€70-100 (marca da bollo + kit postale)',
        documenti: [
          GuidaDocument(name: 'Passaporto valido (originale + fotocopia)'),
          GuidaDocument(name: '4 foto tessera formato passaporto'),
          GuidaDocument(name: 'Marca da bollo da €16,00'),
          GuidaDocument(name: 'Kit postale per permesso di soggiorno'),
          GuidaDocument(name: 'Codice fiscale'),
          GuidaDocument(name: 'Contratto di lavoro / iscrizione universitaria'),
          GuidaDocument(name: 'Dichiarazione di ospitalità o contratto di affitto'),
          GuidaDocument(name: 'Assicurazione sanitaria (se richiesta)'),
        ],
        steps: [
          GuidaStep(
            title: 'Compra il Kit Postale',
            description: 'Vai in un ufficio postale abilitato e chiedi il "Kit per permesso di soggiorno". Costa circa €30. Contiene il modulo da compilare e la busta.',
          ),
          GuidaStep(
            title: 'Compila il Modulo',
            description: 'Compila il modulo nel kit con i tuoi dati personali, motivo del soggiorno, indirizzo in Italia. Scrivi in STAMPATELLO e in modo leggibile.',
          ),
          GuidaStep(
            title: 'Prepara i Documenti',
            description: 'Raccogli tutti i documenti richiesti: passaporto, foto, marca da bollo, contratto di lavoro/studio, alloggio.',
          ),
          GuidaStep(
            title: 'Invia alla Posta',
            description: 'Torna all\'ufficio postale con il kit compilato e tutti i documenti. L\'operatore verificherà e invierà tutto. Ti darà una ricevuta con il numero di pratica.',
          ),
          GuidaStep(
            title: 'Attendi la Convocazione',
            description: 'Riceverai un SMS/lettera dalla Questura con la data per le impronte digitali. Possono volerci 30-60 giorni.',
          ),
          GuidaStep(
            title: 'Vai in Questura',
            description: 'Presentati alla Questura nella data indicata con tutti i documenti ORIGINALI. Ti prenderanno le impronte digitali.',
          ),
          GuidaStep(
            title: 'Ritira il Permesso',
            description: 'Riceverai un altro SMS quando il permesso è pronto. Vai in Questura a ritirarlo con la ricevuta e il passaporto.',
          ),
        ],
        linkUtili: [
          'https://www.portaleimmigrazione.it',
          'https://www.poliziadistato.it/articolo/permesso-di-soggiorno',
        ],
      ),
      Guida(
        id: 2,
        title: 'Rinnovo Permesso di Soggiorno',
        shortDescription: 'Come rinnovare il permesso prima della scadenza',
        icon: Icons.refresh,
        color: AppColors.iconGreen,
        category: 'Permesso',
        tempiStimati: '60-120 giorni',
        costoStimato: '€80-130',
        documenti: [
          GuidaDocument(name: 'Permesso di soggiorno scaduto/in scadenza'),
          GuidaDocument(name: 'Passaporto valido'),
          GuidaDocument(name: '4 foto tessera'),
          GuidaDocument(name: 'Marca da bollo da €16,00'),
          GuidaDocument(name: 'Kit postale'),
          GuidaDocument(name: 'Contratto di lavoro in corso'),
          GuidaDocument(name: 'Dichiarazione dei redditi / CU'),
          GuidaDocument(name: 'Contratto di affitto registrato'),
          GuidaDocument(name: 'Certificato di residenza'),
        ],
        steps: [
          GuidaStep(title: 'Controlla la Scadenza', description: 'Inizia il rinnovo ALMENO 60 giorni PRIMA della scadenza. Puoi rinnovare fino a 60 giorni DOPO la scadenza.'),
          GuidaStep(title: 'Compra il Kit Postale', description: 'Vai all\'ufficio postale e acquista il kit per rinnovo permesso.'),
          GuidaStep(title: 'Compila e Invia', description: 'Compila il modulo indicando "RINNOVO" e allega tutti i documenti aggiornati.'),
          GuidaStep(title: 'Attendi Convocazione', description: 'La Questura ti convocherà per le impronte e la verifica documenti.'),
          GuidaStep(title: 'Ritira il Nuovo Permesso', description: 'Quando pronto, ritira in Questura.'),
        ],
        linkUtili: ['https://www.portaleimmigrazione.it'],
      ),
      Guida(
        id: 3,
        title: 'Ricongiungimento Familiare',
        shortDescription: 'Come portare la tua famiglia in Italia',
        icon: Icons.family_restroom,
        color: AppColors.iconOrange,
        category: 'Famiglia',
        tempiStimati: '6-12 mesi',
        costoStimato: '€200-500 (visto + documenti)',
        documenti: [
          GuidaDocument(name: 'Permesso di soggiorno valido (almeno 1 anno)'),
          GuidaDocument(name: 'Passaporto'),
          GuidaDocument(name: 'Certificato di matrimonio (tradotto e legalizzato)'),
          GuidaDocument(name: 'Certificato di nascita figli (tradotto e legalizzato)'),
          GuidaDocument(name: 'Dichiarazione dei redditi (reddito minimo richiesto)'),
          GuidaDocument(name: 'Contratto di affitto + idoneità alloggiativa'),
          GuidaDocument(name: 'Certificato di residenza'),
          GuidaDocument(name: 'Assicurazione sanitaria per i familiari'),
        ],
        steps: [
          GuidaStep(title: 'Verifica i Requisiti', description: 'Devi avere: permesso di soggiorno di almeno 1 anno, reddito minimo (€8.500 + €5.900 per ogni familiare), alloggio idoneo.'),
          GuidaStep(title: 'Richiedi Nulla Osta', description: 'Presenta domanda online su portaleimmigrazione.it per il nulla osta al ricongiungimento familiare.'),
          GuidaStep(title: 'Idoneità Alloggiativa', description: 'Richiedi al Comune il certificato di idoneità alloggiativa. Verificano che la casa sia abbastanza grande.'),
          GuidaStep(title: 'Attendi il Nulla Osta', description: 'La Prefettura esamina la domanda (90-180 giorni). Se approvata, invia il nulla osta.'),
          GuidaStep(title: 'Visto per i Familiari', description: 'I tuoi familiari devono andare al Consolato/Ambasciata italiana nel loro paese con il nulla osta per ottenere il visto.'),
          GuidaStep(title: 'Arrivo in Italia', description: 'Entro 8 giorni dall\'arrivo, i familiari devono richiedere il permesso di soggiorno.'),
        ],
        linkUtili: ['https://www.portaleimmigrazione.it'],
      ),
      Guida(
        id: 4,
        title: 'Cittadinanza Italiana',
        shortDescription: 'Come ottenere la cittadinanza per matrimonio o residenza',
        icon: Icons.flag,
        color: AppColors.iconPurple,
        category: 'Cittadinanza',
        tempiStimati: '2-4 anni (dalla domanda)',
        costoStimato: '€250 (contributo)',
        documenti: [
          GuidaDocument(name: 'Certificato di nascita (tradotto e legalizzato)'),
          GuidaDocument(name: 'Certificato penale del paese di origine'),
          GuidaDocument(name: 'Passaporto'),
          GuidaDocument(name: 'Permesso di soggiorno'),
          GuidaDocument(name: 'Certificato di residenza storico'),
          GuidaDocument(name: 'Dichiarazione dei redditi (ultimi 3 anni)'),
          GuidaDocument(name: 'Certificato di matrimonio (se per matrimonio)'),
          GuidaDocument(name: 'Certificato B1 di italiano'),
        ],
        steps: [
          GuidaStep(title: 'Verifica i Requisiti', description: 'Per residenza: 10 anni di residenza legale (4 anni per UE, 5 per apolidi/rifugiati). Per matrimonio: 2 anni di residenza o 3 anni di matrimonio se residente all\'estero.'),
          GuidaStep(title: 'Certificato di Italiano B1', description: 'Devi avere almeno il livello B1 di italiano certificato (CILS, CELI, PLIDA o equivalente).'),
          GuidaStep(title: 'Presenta Domanda Online', description: 'Vai su https://portaleservizi.interno.it e presenta la domanda di cittadinanza con tutti i documenti.'),
          GuidaStep(title: 'Paga il Contributo', description: 'Paga €250 tramite bollettino postale al momento della domanda.'),
          GuidaStep(title: 'Attendi la Risposta', description: 'Il Ministero ha fino a 24 mesi per rispondere (spesso di più). Controlla online lo stato.'),
          GuidaStep(title: 'Giuramento', description: 'Se approvata, entro 6 mesi devi giurare fedeltà alla Repubblica al Comune di residenza.'),
        ],
        linkUtili: ['https://portaleservizi.interno.it'],
      ),
      Guida(
        id: 5,
        title: 'Carta di Soggiorno Lungo Periodo',
        shortDescription: 'Permesso permanente dopo 5 anni di residenza',
        icon: Icons.card_membership,
        color: AppColors.iconGreen,
        category: 'Permesso',
        tempiStimati: '90 giorni',
        costoStimato: '€100-150',
        documenti: [
          GuidaDocument(name: 'Permesso di soggiorno valido da almeno 5 anni'),
          GuidaDocument(name: 'Passaporto'),
          GuidaDocument(name: 'Dichiarazione dei redditi (reddito minimo)'),
          GuidaDocument(name: 'Certificato di idoneità alloggiativa'),
          GuidaDocument(name: 'Certificato di italiano A2'),
        ],
        steps: [
          GuidaStep(title: 'Verifica 5 Anni', description: 'Devi avere 5 anni di residenza legale continuativa in Italia.'),
          GuidaStep(title: 'Test Italiano A2', description: 'Devi avere certificato di italiano almeno A2.'),
          GuidaStep(title: 'Invia Domanda', description: 'Kit postale come per il permesso, ma seleziona "Carta di soggiorno CE".'),
          GuidaStep(title: 'Ritira', description: 'Dopo approvazione, ritira in Questura. La carta è a tempo indeterminato!'),
        ],
        linkUtili: [],
      ),
      Guida(
        id: 6,
        title: 'Nulla Osta Lavoro',
        shortDescription: 'Autorizzazione per lavorare in Italia',
        icon: Icons.work,
        color: AppColors.iconBlue,
        category: 'Lavoro',
        tempiStimati: '30-60 giorni',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'Domanda del datore di lavoro'),
          GuidaDocument(name: 'Contratto di lavoro'),
          GuidaDocument(name: 'Documenti del lavoratore'),
        ],
        steps: [
          GuidaStep(title: 'Il Datore Presenta Domanda', description: 'Il datore di lavoro deve presentare domanda allo Sportello Unico Immigrazione.'),
          GuidaStep(title: 'Verifica Quote', description: 'Verifica che ci siano quote disponibili nel Decreto Flussi annuale.'),
          GuidaStep(title: 'Rilascio Nulla Osta', description: 'Lo Sportello Unico rilascia il nulla osta al lavoro.'),
          GuidaStep(title: 'Visto e Permesso', description: 'Il lavoratore ottiene il visto al Consolato e poi il permesso in Italia.'),
        ],
        linkUtili: [],
      ),
      Guida(
        id: 7,
        title: 'ADI - Assegno di Inclusione',
        shortDescription: 'Come richiedere l\'assegno di inclusione',
        icon: Icons.euro,
        color: AppColors.iconOrange,
        category: 'Benefici',
        tempiStimati: '30 giorni',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'ISEE in corso di validità'),
          GuidaDocument(name: 'Documento di identità'),
          GuidaDocument(name: 'Permesso di soggiorno lungo periodo o 5+ anni'),
          GuidaDocument(name: 'Residenza in Italia da almeno 5 anni (ultimi 2 continuativi)'),
        ],
        steps: [
          GuidaStep(title: 'Fai l\'ISEE', description: 'Vai al CAF e fai l\'ISEE. Deve essere sotto €9.360.'),
          GuidaStep(title: 'Domanda su INPS', description: 'Presenta domanda online su inps.it o tramite patronato.'),
          GuidaStep(title: 'Sottoscrivi il PAD', description: 'Vai al Centro per l\'Impiego per il Patto di Attivazione Digitale.'),
          GuidaStep(title: 'Ricevi il Pagamento', description: 'Se approvato, ricevi la carta di inclusione con l\'importo mensile.'),
        ],
        linkUtili: ['https://www.inps.it'],
      ),
      Guida(
        id: 8,
        title: 'Codice Fiscale',
        shortDescription: 'Come richiedere o duplicare il codice fiscale',
        icon: Icons.credit_card,
        color: AppColors.iconPurple,
        category: 'Documenti',
        tempiStimati: 'Immediato - 5 giorni',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'Passaporto o documento di identità'),
          GuidaDocument(name: 'Permesso di soggiorno (o ricevuta)'),
        ],
        steps: [
          GuidaStep(title: 'Vai all\'Agenzia delle Entrate', description: 'Cerca l\'ufficio più vicino su agenziaentrate.gov.it. Prenota appuntamento online.'),
          GuidaStep(title: 'Presenta i Documenti', description: 'Porta passaporto e permesso. Il codice fiscale viene rilasciato subito.'),
          GuidaStep(title: 'Per Duplicato', description: 'Se lo hai perso, stessa procedura. Puoi anche richiederlo online con SPID.'),
        ],
        linkUtili: ['https://www.agenziaentrate.gov.it'],
      ),
      Guida(
        id: 9,
        title: 'Tessera Sanitaria',
        shortDescription: 'Come ottenere la tessera sanitaria e iscriversi al SSN',
        icon: Icons.local_hospital,
        color: AppColors.iconBlue,
        category: 'Sanità',
        tempiStimati: '1-7 giorni',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'Codice fiscale'),
          GuidaDocument(name: 'Permesso di soggiorno'),
          GuidaDocument(name: 'Certificato di residenza'),
          GuidaDocument(name: 'Autocertificazione di residenza'),
        ],
        steps: [
          GuidaStep(title: 'Vai alla ASL', description: 'Vai alla ASL del tuo Comune di residenza con i documenti.'),
          GuidaStep(title: 'Iscrizione al SSN', description: 'Compila il modulo di iscrizione al Servizio Sanitario Nazionale.'),
          GuidaStep(title: 'Scegli il Medico', description: 'Scegli il medico di base dalla lista disponibile.'),
          GuidaStep(title: 'Ricevi la Tessera', description: 'Ti danno un certificato provvisorio. La tessera arriva per posta in 1-2 settimane.'),
        ],
        linkUtili: [],
      ),
      Guida(
        id: 10,
        title: 'Iscrizione Anagrafe (Residenza)',
        shortDescription: 'Come ottenere la residenza nel Comune',
        icon: Icons.home,
        color: AppColors.iconGreen,
        category: 'Documenti',
        tempiStimati: '45 giorni (verifica vigile)',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'Passaporto'),
          GuidaDocument(name: 'Permesso di soggiorno (o ricevuta)'),
          GuidaDocument(name: 'Codice fiscale'),
          GuidaDocument(name: 'Contratto di affitto registrato'),
        ],
        steps: [
          GuidaStep(title: 'Vai all\'Anagrafe', description: 'Vai all\'ufficio anagrafe del Comune dove abiti.'),
          GuidaStep(title: 'Compila la Dichiarazione', description: 'Compila il modulo di richiesta residenza.'),
          GuidaStep(title: 'Verifica del Vigile', description: 'Un vigile verrà a verificare che abiti davvero lì. Entro 45 giorni.'),
          GuidaStep(title: 'Certificato', description: 'Se la verifica è positiva, sei ufficialmente residente. Puoi richiedere il certificato.'),
        ],
        linkUtili: [],
      ),
      Guida(
        id: 11,
        title: 'Come Creare SPID',
        shortDescription: 'Identità digitale per accedere ai servizi online',
        icon: Icons.fingerprint,
        color: AppColors.iconOrange,
        category: 'Digitale',
        tempiStimati: '15-30 minuti',
        costoStimato: 'Gratuito (con Poste)',
        documenti: [
          GuidaDocument(name: 'Carta d\'identità o passaporto'),
          GuidaDocument(name: 'Codice fiscale / tessera sanitaria'),
          GuidaDocument(name: 'Email personale'),
          GuidaDocument(name: 'Numero di cellulare'),
        ],
        steps: [
          GuidaStep(title: 'Scegli il Provider', description: 'Poste Italiane (gratis di persona), Aruba, Infocert, Namirial (online a pagamento ~€15-25).'),
          GuidaStep(title: 'Con Poste (Gratis)', description: 'Scarica l\'app PosteID → Registrati → Vai in ufficio postale con documento e codice fiscale per il riconoscimento.'),
          GuidaStep(title: 'Online (a Pagamento)', description: 'Su aruba.it o infocert.it → Registrati → Riconoscimento via webcam → Paghi ~€15-25.'),
          GuidaStep(title: 'Usa lo SPID', description: 'Ora puoi accedere a INPS, Agenzia Entrate, ANPR, Portale Immigrazione e tutti i servizi pubblici.'),
        ],
        linkUtili: ['https://www.spid.gov.it'],
      ),
      Guida(
        id: 12,
        title: 'Stato di Famiglia da ANPR',
        shortDescription: 'Scarica gratis lo stato di famiglia online',
        icon: Icons.description,
        color: AppColors.iconPurple,
        category: 'Documenti',
        tempiStimati: '5 minuti',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'SPID o CIE attivata'),
        ],
        steps: [
          GuidaStep(title: 'Accedi ad ANPR', description: 'Vai su anagrafenazionale.interno.it e accedi con SPID o CIE.'),
          GuidaStep(title: 'Richiedi Certificato', description: 'Clicca "Richiesta certificato" → Seleziona "Stato di famiglia".'),
          GuidaStep(title: 'Scarica PDF', description: 'Il certificato viene generato in PDF istantaneamente. Scaricalo e stampalo.'),
        ],
        linkUtili: ['https://www.anagrafenazionale.interno.it'],
      ),
      Guida(
        id: 13,
        title: 'Appuntamento Agenzia Entrate',
        shortDescription: 'Come prenotare un appuntamento',
        icon: Icons.event,
        color: AppColors.iconBlue,
        category: 'Documenti',
        tempiStimati: '5-10 minuti per prenotare',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'Codice fiscale'),
          GuidaDocument(name: 'Documento di identità'),
        ],
        steps: [
          GuidaStep(title: 'Vai sul Sito', description: 'Vai su agenziaentrate.gov.it → Contatta e prenota.'),
          GuidaStep(title: 'Prenota Online', description: 'Seleziona la provincia, l\'ufficio, il servizio e la data disponibile.'),
          GuidaStep(title: 'Presentati', description: 'Vai all\'appuntamento con i tuoi documenti. Arriva 10 minuti prima.'),
        ],
        linkUtili: ['https://www.agenziaentrate.gov.it/portale/prenota-un-appuntamento'],
      ),
      Guida(
        id: 14,
        title: 'Iscrizione ASL',
        shortDescription: 'Come iscriversi all\'Azienda Sanitaria Locale',
        icon: Icons.medical_services,
        color: AppColors.iconGreen,
        category: 'Sanità',
        tempiStimati: '1 giorno',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'Codice fiscale'),
          GuidaDocument(name: 'Permesso di soggiorno'),
          GuidaDocument(name: 'Certificato di residenza'),
        ],
        steps: [
          GuidaStep(title: 'Trova la Tua ASL', description: 'Cerca l\'ASL del tuo Comune su Google: "ASL + nome città".'),
          GuidaStep(title: 'Vai allo Sportello', description: 'Porta tutti i documenti e compila il modulo di iscrizione.'),
          GuidaStep(title: 'Scegli il Medico', description: 'Ti daranno la lista dei medici di base disponibili nella tua zona.'),
        ],
        linkUtili: [],
      ),
      Guida(
        id: 15,
        title: 'Attivare la PEC',
        shortDescription: 'Posta Elettronica Certificata',
        icon: Icons.email,
        color: AppColors.iconOrange,
        category: 'Digitale',
        tempiStimati: '10 minuti',
        costoStimato: '€5-10/anno',
        documenti: [
          GuidaDocument(name: 'Documento di identità'),
          GuidaDocument(name: 'Codice fiscale'),
        ],
        steps: [
          GuidaStep(title: 'Scegli un Provider', description: 'Aruba PEC (€5/anno), Legalmail, Register.it, Poste Italiane.'),
          GuidaStep(title: 'Registrati', description: 'Vai sul sito del provider, inserisci i tuoi dati e scegli l\'indirizzo PEC.'),
          GuidaStep(title: 'Paga', description: 'Paga l\'abbonamento annuale (€5-10).'),
          GuidaStep(title: 'Usa la PEC', description: 'Ora puoi inviare comunicazioni ufficiali a PA, tribunali, aziende con valore legale.'),
        ],
        linkUtili: ['https://www.pec.it'],
      ),
      Guida(
        id: 16,
        title: 'Carta d\'Identità Elettronica (CIE)',
        shortDescription: 'Come richiedere la CIE',
        icon: Icons.perm_identity,
        color: AppColors.iconPurple,
        category: 'Documenti',
        tempiStimati: '6 giorni lavorativi',
        costoStimato: '€22,21',
        documenti: [
          GuidaDocument(name: 'Permesso di soggiorno valido'),
          GuidaDocument(name: 'Codice fiscale'),
          GuidaDocument(name: 'Una fototessera recente'),
          GuidaDocument(name: 'Vecchia carta d\'identità (se rinnovo)'),
        ],
        steps: [
          GuidaStep(title: 'Prenota Online', description: 'Vai su prenotazionicie.interno.gov.it → Cerca il tuo Comune → Prenota.'),
          GuidaStep(title: 'Vai al Comune', description: 'Presentati all\'appuntamento con i documenti e la fototessera.'),
          GuidaStep(title: 'Paga', description: 'Paga €22,21 (contanti o POS in base al Comune).'),
          GuidaStep(title: 'Ricevi a Casa', description: 'La CIE arriva per posta raccomandata in 6 giorni lavorativi.'),
        ],
        linkUtili: ['https://prenotazionicie.interno.gov.it'],
      ),
      Guida(
        id: 17,
        title: 'ISEE - Come Farlo e Dove',
        shortDescription: 'Indicatore della Situazione Economica',
        icon: Icons.calculate,
        color: AppColors.iconBlue,
        category: 'Benefici',
        tempiStimati: '1-2 settimane',
        costoStimato: 'Gratuito (al CAF)',
        documenti: [
          GuidaDocument(name: 'Documento di identità di tutti i componenti'),
          GuidaDocument(name: 'Codice fiscale di tutti'),
          GuidaDocument(name: 'Dichiarazione dei redditi (730 o CU)'),
          GuidaDocument(name: 'Saldo e giacenza media conti correnti'),
          GuidaDocument(name: 'Certificati catastali (se proprietari)'),
          GuidaDocument(name: 'Contratto di affitto'),
          GuidaDocument(name: 'Targa auto/moto'),
        ],
        steps: [
          GuidaStep(title: 'Raccogli i Documenti', description: 'Tutti i redditi e patrimoni di OGNI membro della famiglia.'),
          GuidaStep(title: 'Vai al CAF', description: 'Cerca il CAF più vicino (CGIL, CISL, UIL, ACLI). Il servizio ISEE è GRATUITO.'),
          GuidaStep(title: 'Compila la DSU', description: 'Il CAF ti aiuta a compilare la Dichiarazione Sostitutiva Unica.'),
          GuidaStep(title: 'Ricevi l\'ISEE', description: 'In 1-2 settimane l\'INPS calcola il tuo ISEE. Lo trovi su inps.it.'),
        ],
        linkUtili: ['https://www.inps.it/servizi-online/isee'],
      ),
      Guida(
        id: 18,
        title: 'CU - Certificazione Unica',
        shortDescription: 'Come scaricare la Certificazione Unica',
        icon: Icons.receipt_long,
        color: AppColors.iconGreen,
        category: 'Lavoro',
        tempiStimati: '5 minuti',
        costoStimato: 'Gratuito',
        documenti: [
          GuidaDocument(name: 'SPID o CIE per accesso online'),
        ],
        steps: [
          GuidaStep(title: 'Accedi a INPS', description: 'Vai su inps.it → Accedi con SPID o CIE.'),
          GuidaStep(title: 'Cerca CU', description: 'Cerca "Certificazione Unica" nella barra di ricerca.'),
          GuidaStep(title: 'Scarica', description: 'Seleziona l\'anno e scarica il PDF della tua CU.'),
        ],
        linkUtili: ['https://www.inps.it'],
      ),
    ];
  }

  static List<String> getCategories() {
    return ['Tutti', 'Permesso', 'Famiglia', 'Cittadinanza', 'Lavoro', 'Benefici', 'Documenti', 'Sanità', 'Digitale'];
  }
}
