// Hard-coded translations for the onboarding screen. Kept here (not via
// Gemini) so the first-launch welcome works 100% offline and instantly.

class OnboardingStrings {
  final String welcome;
  final String subtitle;
  final String whatYouFind;
  final String feat1Title;
  final String feat1Desc;
  final String feat2Title;
  final String feat2Desc;
  final String feat3Title;
  final String feat3Desc;
  final String feat4Title;
  final String feat4Desc;
  final String start;
  final String next;
  final String back;

  const OnboardingStrings({
    required this.welcome,
    required this.subtitle,
    required this.whatYouFind,
    required this.feat1Title,
    required this.feat1Desc,
    required this.feat2Title,
    required this.feat2Desc,
    required this.feat3Title,
    required this.feat3Desc,
    required this.feat4Title,
    required this.feat4Desc,
    required this.start,
    required this.next,
    required this.back,
  });
}

OnboardingStrings onboardingFor(String code) =>
    _translations[code] ?? _translations['en']!;

const _translations = <String, OnboardingStrings>{
  'it': OnboardingStrings(
    welcome: 'Benvenuto!',
    subtitle: 'La guida completa per vivere in Italia',
    whatYouFind: 'Ecco cosa trovi dentro',
    feat1Title: 'Guida Documenti',
    feat1Desc: 'Dalla richiesta di asilo alla cittadinanza, in 14 lingue',
    feat2Title: 'Scanner & Portafoglio',
    feat2Desc: 'Salva passaporto, permesso di soggiorno, patente',
    feat3Title: 'Traduttore',
    feat3Desc: 'Traduci testi, voce e foto di documenti',
    feat4Title: 'Tracker Pratica',
    feat4Desc: 'Tieni traccia delle tue domande',
    start: 'Inizia',
    next: 'Avanti',
    back: 'Indietro',
  ),
  'en': OnboardingStrings(
    welcome: 'Welcome!',
    subtitle: 'The complete guide to living in Italy',
    whatYouFind: "Here's what you'll find",
    feat1Title: 'Document Guide',
    feat1Desc: 'From asylum request to citizenship, in 14 languages',
    feat2Title: 'Scanner & Wallet',
    feat2Desc: "Save passport, residence permit, driver's license",
    feat3Title: 'Translator',
    feat3Desc: 'Translate text, voice and document photos',
    feat4Title: 'Case Tracker',
    feat4Desc: 'Keep track of your applications',
    start: 'Start',
    next: 'Next',
    back: 'Back',
  ),
  'ar': OnboardingStrings(
    welcome: 'مرحباً!',
    subtitle: 'الدليل الكامل للعيش في إيطاليا',
    whatYouFind: 'إليك ما ستجده',
    feat1Title: 'دليل الوثائق',
    feat1Desc: 'من طلب اللجوء إلى الجنسية، ب 14 لغة',
    feat2Title: 'الماسح والمحفظة',
    feat2Desc: 'احفظ جواز السفر وتصريح الإقامة ورخصة القيادة',
    feat3Title: 'المترجم',
    feat3Desc: 'ترجم النصوص والصوت وصور الوثائق',
    feat4Title: 'متتبع الطلبات',
    feat4Desc: 'تتبع طلباتك',
    start: 'ابدأ',
    next: 'التالي',
    back: 'السابق',
  ),
  'sq': OnboardingStrings(
    welcome: 'Mirë se vini!',
    subtitle: 'Udhërrëfyesi i plotë për të jetuar në Itali',
    whatYouFind: 'Ja çfarë do të gjesh',
    feat1Title: 'Udhëzues Dokumentesh',
    feat1Desc: 'Nga kërkesa për azil deri në shtetësi, në 14 gjuhë',
    feat2Title: 'Skaneri & Portofoli',
    feat2Desc: 'Ruaj pasaportën, lejen e qëndrimit, patentën',
    feat3Title: 'Përkthyes',
    feat3Desc: 'Përkthe tekst, zë dhe foto dokumentesh',
    feat4Title: 'Ndjekës Procedurash',
    feat4Desc: 'Mbaj shënim aplikimet e tua',
    start: 'Fillo',
    next: 'Përpara',
    back: 'Prapa',
  ),
  'ro': OnboardingStrings(
    welcome: 'Bun venit!',
    subtitle: 'Ghidul complet pentru a trăi în Italia',
    whatYouFind: 'Iată ce vei găsi',
    feat1Title: 'Ghid Documente',
    feat1Desc: 'De la cererea de azil până la cetățenie, în 14 limbi',
    feat2Title: 'Scaner și Portofel',
    feat2Desc: 'Salvează pașaport, permis de ședere, permis auto',
    feat3Title: 'Traducător',
    feat3Desc: 'Traduce text, voce și fotografii de documente',
    feat4Title: 'Tracker Cereri',
    feat4Desc: 'Urmărește cererile tale',
    start: 'Începe',
    next: 'Înainte',
    back: 'Înapoi',
  ),
  'zh': OnboardingStrings(
    welcome: '欢迎!',
    subtitle: '在意大利生活的完整指南',
    whatYouFind: '这里有什么',
    feat1Title: '证件指南',
    feat1Desc: '从庇护申请到国籍,提供14种语言',
    feat2Title: '扫描与钱包',
    feat2Desc: '保存护照、居留证、驾照',
    feat3Title: '翻译器',
    feat3Desc: '翻译文字、语音和证件照片',
    feat4Title: '案件追踪',
    feat4Desc: '跟踪您的申请',
    start: '开始',
    next: '下一步',
    back: '返回',
  ),
  'bn': OnboardingStrings(
    welcome: 'স্বাগতম!',
    subtitle: 'ইতালিতে বসবাসের সম্পূর্ণ গাইড',
    whatYouFind: 'এখানে কী পাবেন',
    feat1Title: 'কাগজপত্র গাইড',
    feat1Desc: 'আশ্রয় আবেদন থেকে নাগরিকত্ব পর্যন্ত, 14টি ভাষায়',
    feat2Title: 'স্ক্যানার ও ওয়ালেট',
    feat2Desc: 'পাসপোর্ট, পারমেসো ডি সোজ্জর্নো, ড্রাইভিং লাইসেন্স সংরক্ষণ করুন',
    feat3Title: 'অনুবাদক',
    feat3Desc: 'টেক্সট, ভয়েস এবং ডকুমেন্ট ছবি অনুবাদ করুন',
    feat4Title: 'মামলা ট্র্যাকার',
    feat4Desc: 'আপনার আবেদনগুলি ট্র্যাক করুন',
    start: 'শুরু করুন',
    next: 'পরবর্তী',
    back: 'পিছনে',
  ),
  'ur': OnboardingStrings(
    welcome: 'خوش آمدید!',
    subtitle: 'اٹلی میں رہنے کی مکمل گائیڈ',
    whatYouFind: 'یہاں آپ کو کیا ملے گا',
    feat1Title: 'دستاویزات کی گائیڈ',
    feat1Desc: 'پناہ کی درخواست سے شہریت تک، 14 زبانوں میں',
    feat2Title: 'اسکینر اور والیٹ',
    feat2Desc: 'پاسپورٹ، اقامت اور ڈرائیونگ لائسنس محفوظ کریں',
    feat3Title: 'مترجم',
    feat3Desc: 'متن، آواز اور دستاویز کی تصاویر کا ترجمہ کریں',
    feat4Title: 'کیس ٹریکر',
    feat4Desc: 'اپنی درخواستوں کو ٹریک کریں',
    start: 'شروع کریں',
    next: 'اگلا',
    back: 'پیچھے',
  ),
  'uk': OnboardingStrings(
    welcome: 'Ласкаво просимо!',
    subtitle: 'Повний посібник для життя в Італії',
    whatYouFind: 'Ось що ви знайдете',
    feat1Title: 'Довідник документів',
    feat1Desc: 'Від запиту на притулок до громадянства, 14 мовами',
    feat2Title: 'Сканер і гаманець',
    feat2Desc: 'Зберігайте паспорт, дозвіл на проживання, права',
    feat3Title: 'Перекладач',
    feat3Desc: 'Перекладайте текст, голос і фото документів',
    feat4Title: 'Трекер справ',
    feat4Desc: 'Відстежуйте свої заяви',
    start: 'Почати',
    next: 'Далі',
    back: 'Назад',
  ),
  'fr': OnboardingStrings(
    welcome: 'Bienvenue!',
    subtitle: 'Le guide complet pour vivre en Italie',
    whatYouFind: 'Voici ce que vous trouverez',
    feat1Title: 'Guide des documents',
    feat1Desc: "De la demande d'asile à la citoyenneté, en 14 langues",
    feat2Title: 'Scanner & Portefeuille',
    feat2Desc: 'Enregistrez passeport, titre de séjour, permis',
    feat3Title: 'Traducteur',
    feat3Desc: 'Traduisez textes, voix et photos de documents',
    feat4Title: 'Suivi des dossiers',
    feat4Desc: 'Suivez vos demandes',
    start: 'Commencer',
    next: 'Suivant',
    back: 'Retour',
  ),
  'hi': OnboardingStrings(
    welcome: 'स्वागत है!',
    subtitle: 'इटली में रहने के लिए संपूर्ण गाइड',
    whatYouFind: 'यहाँ आपको मिलेगा',
    feat1Title: 'दस्तावेज़ गाइड',
    feat1Desc: 'शरण के आवेदन से नागरिकता तक, 14 भाषाओं में',
    feat2Title: 'स्कैनर और वॉलेट',
    feat2Desc: 'पासपोर्ट, रेज़िडेंसी परमिट, ड्राइविंग लाइसेंस सहेजें',
    feat3Title: 'अनुवादक',
    feat3Desc: 'टेक्स्ट, आवाज़ और दस्तावेज़ फ़ोटो का अनुवाद करें',
    feat4Title: 'केस ट्रैकर',
    feat4Desc: 'अपने आवेदनों को ट्रैक करें',
    start: 'शुरू करें',
    next: 'अगला',
    back: 'पीछे',
  ),
  'pa': OnboardingStrings(
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ!',
    subtitle: 'ਇਟਲੀ ਵਿੱਚ ਰਹਿਣ ਲਈ ਸੰਪੂਰਨ ਗਾਈਡ',
    whatYouFind: 'ਇੱਥੇ ਤੁਹਾਨੂੰ ਕੀ ਮਿਲੇਗਾ',
    feat1Title: 'ਦਸਤਾਵੇਜ਼ ਗਾਈਡ',
    feat1Desc: 'ਸ਼ਰਣ ਦੀ ਅਰਜ਼ੀ ਤੋਂ ਨਾਗਰਿਕਤਾ ਤੱਕ, 14 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ',
    feat2Title: 'ਸਕੈਨਰ ਅਤੇ ਵਾਲੇਟ',
    feat2Desc: 'ਪਾਸਪੋਰਟ, ਰਿਹਾਇਸ਼ ਪਰਮਿਟ, ਡਰਾਈਵਿੰਗ ਲਾਈਸੈਂਸ ਸੰਭਾਲੋ',
    feat3Title: 'ਅਨੁਵਾਦਕ',
    feat3Desc: 'ਟੈਕਸਟ, ਆਵਾਜ਼ ਅਤੇ ਦਸਤਾਵੇਜ਼ ਫੋਟੋਆਂ ਦਾ ਅਨੁਵਾਦ ਕਰੋ',
    feat4Title: 'ਕੇਸ ਟ੍ਰੈਕਰ',
    feat4Desc: 'ਆਪਣੀਆਂ ਅਰਜ਼ੀਆਂ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ',
    start: 'ਸ਼ੁਰੂ ਕਰੋ',
    next: 'ਅੱਗੇ',
    back: 'ਪਿੱਛੇ',
  ),
  'es': OnboardingStrings(
    welcome: '¡Bienvenido!',
    subtitle: 'La guía completa para vivir en Italia',
    whatYouFind: 'Esto es lo que encontrarás',
    feat1Title: 'Guía de Documentos',
    feat1Desc: 'Del asilo a la ciudadanía, en 14 idiomas',
    feat2Title: 'Escáner y Cartera',
    feat2Desc: 'Guarda pasaporte, permiso de residencia, carnet',
    feat3Title: 'Traductor',
    feat3Desc: 'Traduce textos, voz y fotos de documentos',
    feat4Title: 'Seguidor de Trámites',
    feat4Desc: 'Sigue tus solicitudes',
    start: 'Empezar',
    next: 'Siguiente',
    back: 'Atrás',
  ),
  'ru': OnboardingStrings(
    welcome: 'Добро пожаловать!',
    subtitle: 'Полное руководство по жизни в Италии',
    whatYouFind: 'Вот что вас ждет',
    feat1Title: 'Руководство по документам',
    feat1Desc: 'От прошения об убежище до гражданства, на 14 языках',
    feat2Title: 'Сканер и кошелёк',
    feat2Desc: 'Сохраняйте паспорт, вид на жительство, права',
    feat3Title: 'Переводчик',
    feat3Desc: 'Переводите текст, голос и фотографии документов',
    feat4Title: 'Трекер заявок',
    feat4Desc: 'Отслеживайте свои заявления',
    start: 'Начать',
    next: 'Далее',
    back: 'Назад',
  ),
};

/// "Choose your language" in the top languages — displayed stacked on step 1
/// so any newcomer recognises their language at a glance.
const chooseLanguageLabels = <String>[
  'Scegli la tua lingua',
  'Choose your language',
  'اختر لغتك',
  '选择您的语言',
  'Alege limba ta',
  'Виберіть мову',
  'Choisissez votre langue',
  'Elige tu idioma',
  'अपनी भाषा चुनें',
  'اپنی زبان منتخب کریں',
];
