// ---------------------------------------------------------------------------
// AppStrings — traduzioni core dell'app in 8 lingue principali.
// Uso: final s = AppStrings.of(context);  →  s.home, s.ask, s.chooseLanguage...
// Aggiungere una stringa = aggiungere un getter qui + nel map di ogni lingua.
// ---------------------------------------------------------------------------
import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import '../services/language_service.dart';

class AppStrings {
  final String languageCode;
  final Map<String, String> _map;

  const AppStrings._(this.languageCode, this._map);

  static AppStrings of(BuildContext context) {
    final code = context.watch<LanguageService>().currentCode;
    return AppStrings.forCode(code);
  }

  static AppStrings forCode(String code) {
    final map = _allTranslations[code] ?? _allTranslations['it']!;
    return AppStrings._(code, map);
  }

  String get(String key) => _map[key] ?? _allTranslations['it']![key] ?? key;

  bool get isRtl => languageCode == 'ar' || languageCode == 'ur';

  // ── Getters core ──
  String get appName => get('appName');
  String get appTagline => get('appTagline');

  // Welcome / onboarding
  String get chooseLanguage => get('chooseLanguage');
  String get chooseLanguageSubtitle => get('chooseLanguageSubtitle');
  String get continueBtn => get('continueBtn');
  String get welcome => get('welcome');
  String get getStarted => get('getStarted');

  // Bottom nav
  String get navHome => get('navHome');
  String get navBonuses => get('navBonuses');
  String get navAsk => get('navAsk');
  String get navProfile => get('navProfile');

  // Home
  String get homeHeaderTitle => get('homeHeaderTitle');
  String get homeHeaderSubtitle => get('homeHeaderSubtitle');
  String get homeDiscoverRights => get('homeDiscoverRights');
  String get homeDiscoverRightsSub => get('homeDiscoverRightsSub');
  String get homeGuideTitle => get('homeGuideTitle');
  String get homeGuideSub => get('homeGuideSub');
  String get homeToolsTitle => get('homeToolsTitle');
  String get homeToolsSub => get('homeToolsSub');
  String get homeAskTitle => get('homeAskTitle');
  String get homeAskSub => get('homeAskSub');

  // Sbroglia
  String get sbrogliaAsk => get('sbrogliaAsk');
  String get sbrogliaAskPatronato => get('sbrogliaAskPatronato');
  String get sbrogliaSubtitle => get('sbrogliaSubtitle');
  String get sbrogliaWhoAreYou => get('sbrogliaWhoAreYou');
  String get sbrogliaWhoAreYouSub => get('sbrogliaWhoAreYouSub');
  String get sbrogliaInputHint => get('sbrogliaInputHint');

  // Bonus / Il Mio Caso
  String get uploadIsee => get('uploadIsee');
  String get uploadIseeSub => get('uploadIseeSub');
  String get uploadIseeBtn => get('uploadIseeBtn');
  String get continueWithoutIsee => get('continueWithoutIsee');
  String get discoverMyRights => get('discoverMyRights');
  String get myRightsTitle => get('myRightsTitle');
  String get readingIsee => get('readingIsee');
  String get iseeRead => get('iseeRead');
  String get fillAllAnswers => get('fillAllAnswers');
  String get back => get('back');
  String get next => get('next');

  // Questions
  String get qSex => get('qSex');
  String get qSexMale => get('qSexMale');
  String get qSexFemale => get('qSexFemale');
  String get qCitizenship => get('qCitizenship');
  String get qCitIT => get('qCitIT');
  String get qCitUE => get('qCitUE');
  String get qCitExtraUE => get('qCitExtraUE');
  String get qYearsInItaly => get('qYearsInItaly');
  String get qWorkStatus => get('qWorkStatus');
  String get qEmployee => get('qEmployee');
  String get qSelfEmployed => get('qSelfEmployed');
  String get qUnemployed => get('qUnemployed');
  String get qRetired => get('qRetired');
  String get qStudent => get('qStudent');
  String get qIncome => get('qIncome');
  String get qIncomeHelp => get('qIncomeHelp');
  String get qRenting => get('qRenting');
  String get qYes => get('qYes');
  String get qNo => get('qNo');
  String get qMerit100 => get('qMerit100');
  String get qDisability => get('qDisability');

  // Common
  String get loading => get('loading');
  String get error => get('error');
  String get retry => get('retry');
  String get close => get('close');
  String get search => get('search');
  String get cancel => get('cancel');
  String get save => get('save');
  String get confirm => get('confirm');

  // Notifications
  String get newBonusNotifTitle => get('newBonusNotifTitle');
  String get docExpiryNotifTitle => get('docExpiryNotifTitle');

  // ── Tutte le traduzioni ──
  static const Map<String, Map<String, String>> _allTranslations = {
    'it': _it,
    'en': _en,
    'ar': _ar,
    'ur': _ur,
    'hi': _hi,
    'ro': _ro,
    'fr': _fr,
    'es': _es,
    'sq': _sq,
    'zh': _zh,
    'bn': _bn,
    'uk': _uk,
    'ru': _ru,
    'pa': _pa,
  };

  // ═══════════════════════════════════════════════════════════════════
  // ITALIANO (base)
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _it = {
    'appName': 'Il Mio Patronato',
    'appTagline': 'Il Patronato in Tasca',
    'chooseLanguage': 'Scegli la tua lingua',
    'chooseLanguageSubtitle': 'Potrai cambiarla in qualsiasi momento dalle impostazioni',
    'continueBtn': 'Continua',
    'welcome': 'Benvenuto',
    'getStarted': 'Inizia',
    'navHome': 'Home',
    'navBonuses': 'Bonus',
    'navAsk': 'Chiedi',
    'navProfile': 'Profilo',
    'homeHeaderTitle': 'Il Mio Patronato',
    'homeHeaderSubtitle': 'Il Patronato in Tasca',
    'homeDiscoverRights': 'Scopri i tuoi diritti',
    'homeDiscoverRightsSub': 'Carica l\'ISEE e scopri a quali bonus hai diritto',
    'homeGuideTitle': 'Guide e Documenti',
    'homeGuideSub': 'Procedure spiegate passo per passo',
    'homeToolsTitle': 'Strumenti',
    'homeToolsSub': 'Scanner, traduttore, simulatore',
    'homeAskTitle': 'Chiedi al Patronato',
    'homeAskSub': 'Risposta istantanea dell\'AI',
    'sbrogliaAsk': 'CHIEDI',
    'sbrogliaAskPatronato': 'Chiedi al Patronato',
    'sbrogliaSubtitle': 'Fai una domanda — risposta\nistantanea e precisa.',
    'sbrogliaWhoAreYou': 'Chi sei?',
    'sbrogliaWhoAreYouSub': 'Scegli il tuo profilo per risposte\npersonalizzate al 100%',
    'sbrogliaInputHint': 'Chiedi a Sbroglia.AI...',
    'uploadIsee': 'Carica il tuo ISEE',
    'uploadIseeSub': 'L\'AI legge l\'attestazione ISEE (foto o PDF) e compila automaticamente i dati del nucleo.',
    'uploadIseeBtn': 'CARICA ISEE (foto o PDF)',
    'continueWithoutIsee': 'Non ho l\'ISEE — continua senza',
    'discoverMyRights': 'SCOPRI I TUOI DIRITTI',
    'myRightsTitle': 'I Tuoi Diritti',
    'readingIsee': 'Leggo l\'ISEE…',
    'iseeRead': 'ISEE letto. Dati compilati.',
    'fillAllAnswers': 'Completa le risposte',
    'back': 'Indietro',
    'next': 'Avanti',
    'qSex': 'Sesso',
    'qSexMale': 'Uomo',
    'qSexFemale': 'Donna',
    'qCitizenship': 'Cittadinanza',
    'qCitIT': 'Italiana',
    'qCitUE': 'UE',
    'qCitExtraUE': 'Extra-UE',
    'qYearsInItaly': 'Da quanti anni vivi in Italia?',
    'qWorkStatus': 'Situazione lavorativa',
    'qEmployee': 'Dipendente',
    'qSelfEmployed': 'Partita IVA',
    'qUnemployed': 'Disoccupato/a',
    'qRetired': 'Pensionato/a',
    'qStudent': 'Studente',
    'qIncome': 'Reddito personale annuale LORDO',
    'qIncomeHelp': '(diverso dall\'ISEE)',
    'qRenting': 'Vivi in affitto?',
    'qYes': 'Sì',
    'qNo': 'No',
    'qMerit100': 'Hai preso 100/100 al diploma?',
    'qDisability': 'Hai una disabilità riconosciuta?',
    'loading': 'Caricamento…',
    'error': 'Errore',
    'retry': 'Riprova',
    'close': 'Chiudi',
    'search': 'Cerca',
    'cancel': 'Annulla',
    'save': 'Salva',
    'confirm': 'Conferma',
    'newBonusNotifTitle': 'Nuovo bonus disponibile',
    'docExpiryNotifTitle': 'Documento in scadenza',
  };

  // ═══════════════════════════════════════════════════════════════════
  // ENGLISH
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _en = {
    'appName': 'My Patronato',
    'appTagline': 'Italian Bureaucracy in Your Pocket',
    'chooseLanguage': 'Choose your language',
    'chooseLanguageSubtitle': 'You can change it anytime in settings',
    'continueBtn': 'Continue',
    'welcome': 'Welcome',
    'getStarted': 'Get started',
    'navHome': 'Home',
    'navBonuses': 'Bonuses',
    'navAsk': 'Ask',
    'navProfile': 'Profile',
    'homeHeaderTitle': 'My Patronato',
    'homeHeaderSubtitle': 'Italian Bureaucracy in Your Pocket',
    'homeDiscoverRights': 'Discover your rights',
    'homeDiscoverRightsSub': 'Upload your ISEE and find out which bonuses you can claim',
    'homeGuideTitle': 'Guides & Documents',
    'homeGuideSub': 'Procedures explained step by step',
    'homeToolsTitle': 'Tools',
    'homeToolsSub': 'Scanner, translator, simulator',
    'homeAskTitle': 'Ask the Patronato',
    'homeAskSub': 'Instant AI answer',
    'sbrogliaAsk': 'ASK',
    'sbrogliaAskPatronato': 'Ask the Patronato',
    'sbrogliaSubtitle': 'Ask anything — get an instant\nand precise answer.',
    'sbrogliaWhoAreYou': 'Who are you?',
    'sbrogliaWhoAreYouSub': 'Pick your profile for 100%\npersonalized answers',
    'sbrogliaInputHint': 'Ask Sbroglia.AI...',
    'uploadIsee': 'Upload your ISEE',
    'uploadIseeSub': 'The AI reads your ISEE certificate (photo or PDF) and fills in your household data automatically.',
    'uploadIseeBtn': 'UPLOAD ISEE (photo or PDF)',
    'continueWithoutIsee': 'I don\'t have ISEE — continue without',
    'discoverMyRights': 'DISCOVER MY RIGHTS',
    'myRightsTitle': 'Your Rights',
    'readingIsee': 'Reading ISEE…',
    'iseeRead': 'ISEE read. Data filled in.',
    'fillAllAnswers': 'Complete the answers',
    'back': 'Back',
    'next': 'Next',
    'qSex': 'Sex',
    'qSexMale': 'Male',
    'qSexFemale': 'Female',
    'qCitizenship': 'Citizenship',
    'qCitIT': 'Italian',
    'qCitUE': 'EU',
    'qCitExtraUE': 'Non-EU',
    'qYearsInItaly': 'How many years have you lived in Italy?',
    'qWorkStatus': 'Work status',
    'qEmployee': 'Employee',
    'qSelfEmployed': 'Self-employed',
    'qUnemployed': 'Unemployed',
    'qRetired': 'Retired',
    'qStudent': 'Student',
    'qIncome': 'Annual GROSS personal income',
    'qIncomeHelp': '(different from ISEE)',
    'qRenting': 'Do you rent?',
    'qYes': 'Yes',
    'qNo': 'No',
    'qMerit100': 'Did you graduate with top marks (100/100)?',
    'qDisability': 'Do you have a recognized disability?',
    'loading': 'Loading…',
    'error': 'Error',
    'retry': 'Retry',
    'close': 'Close',
    'search': 'Search',
    'cancel': 'Cancel',
    'save': 'Save',
    'confirm': 'Confirm',
    'newBonusNotifTitle': 'New bonus available',
    'docExpiryNotifTitle': 'Document expiring soon',
  };

  // ═══════════════════════════════════════════════════════════════════
  // ARABIC (RTL)
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _ar = {
    'appName': 'باتروناتو الخاص بي',
    'appTagline': 'البيروقراطية الإيطالية في جيبك',
    'chooseLanguage': 'اختر لغتك',
    'chooseLanguageSubtitle': 'يمكنك تغييرها في أي وقت من الإعدادات',
    'continueBtn': 'متابعة',
    'welcome': 'مرحبا',
    'getStarted': 'ابدأ',
    'navHome': 'الرئيسية',
    'navBonuses': 'المكافآت',
    'navAsk': 'اسأل',
    'navProfile': 'الملف',
    'homeHeaderTitle': 'باتروناتو الخاص بي',
    'homeHeaderSubtitle': 'البيروقراطية الإيطالية في جيبك',
    'homeDiscoverRights': 'اكتشف حقوقك',
    'homeDiscoverRightsSub': 'حمّل ISEE واكتشف المكافآت التي يحق لك الحصول عليها',
    'homeGuideTitle': 'الأدلة والوثائق',
    'homeGuideSub': 'إجراءات مشروحة خطوة بخطوة',
    'homeToolsTitle': 'الأدوات',
    'homeToolsSub': 'ماسح، مترجم، محاكي',
    'homeAskTitle': 'اسأل الباتروناتو',
    'homeAskSub': 'إجابة فورية بالذكاء الاصطناعي',
    'sbrogliaAsk': 'اسأل',
    'sbrogliaAskPatronato': 'اسأل الباتروناتو',
    'sbrogliaSubtitle': 'اسأل أي شيء — احصل على إجابة\nفورية ودقيقة.',
    'sbrogliaWhoAreYou': 'من أنت؟',
    'sbrogliaWhoAreYouSub': 'اختر ملفك للحصول على إجابات\nمخصصة 100%',
    'sbrogliaInputHint': 'اسأل Sbroglia.AI...',
    'uploadIsee': 'حمّل ISEE الخاص بك',
    'uploadIseeSub': 'يقرأ الذكاء الاصطناعي شهادة ISEE (صورة أو PDF) ويملأ بيانات الأسرة تلقائياً.',
    'uploadIseeBtn': 'تحميل ISEE (صورة أو PDF)',
    'continueWithoutIsee': 'ليس لدي ISEE — تابع بدونه',
    'discoverMyRights': 'اكتشف حقوقي',
    'myRightsTitle': 'حقوقك',
    'readingIsee': 'قراءة ISEE...',
    'iseeRead': 'تمت قراءة ISEE. تم ملء البيانات.',
    'fillAllAnswers': 'أكمل الإجابات',
    'back': 'رجوع',
    'next': 'التالي',
    'qSex': 'الجنس',
    'qSexMale': 'ذكر',
    'qSexFemale': 'أنثى',
    'qCitizenship': 'الجنسية',
    'qCitIT': 'إيطالية',
    'qCitUE': 'أوروبية',
    'qCitExtraUE': 'من خارج الاتحاد الأوروبي',
    'qYearsInItaly': 'كم سنة عشت في إيطاليا؟',
    'qWorkStatus': 'الوضع المهني',
    'qEmployee': 'موظف',
    'qSelfEmployed': 'عمل حر',
    'qUnemployed': 'عاطل عن العمل',
    'qRetired': 'متقاعد',
    'qStudent': 'طالب',
    'qIncome': 'الدخل الشخصي السنوي الإجمالي',
    'qIncomeHelp': '(يختلف عن ISEE)',
    'qRenting': 'هل تعيش في بيت مستأجر؟',
    'qYes': 'نعم',
    'qNo': 'لا',
    'qMerit100': 'هل حصلت على العلامة القصوى في الشهادة؟',
    'qDisability': 'هل لديك إعاقة معترف بها؟',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'retry': 'إعادة المحاولة',
    'close': 'إغلاق',
    'search': 'بحث',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'confirm': 'تأكيد',
    'newBonusNotifTitle': 'مكافأة جديدة متاحة',
    'docExpiryNotifTitle': 'مستند على وشك الانتهاء',
  };

  // ═══════════════════════════════════════════════════════════════════
  // URDU (RTL) — Pakistani immigrants
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _ur = {
    'appName': 'میرا پیٹروناتو',
    'appTagline': 'اطالوی بیوروکریسی آپ کی جیب میں',
    'chooseLanguage': 'اپنی زبان منتخب کریں',
    'chooseLanguageSubtitle': 'آپ اسے سیٹنگز سے کسی بھی وقت تبدیل کر سکتے ہیں',
    'continueBtn': 'جاری رکھیں',
    'welcome': 'خوش آمدید',
    'getStarted': 'شروع کریں',
    'navHome': 'مرکزی',
    'navBonuses': 'بونس',
    'navAsk': 'پوچھیں',
    'navProfile': 'پروفائل',
    'homeHeaderTitle': 'میرا پیٹروناتو',
    'homeHeaderSubtitle': 'اطالوی بیوروکریسی آپ کی جیب میں',
    'homeDiscoverRights': 'اپنے حقوق جانیں',
    'homeDiscoverRightsSub': 'ISEE اپلوڈ کریں اور جانیں کون سے بونس ملیں گے',
    'homeGuideTitle': 'گائیڈ اور دستاویزات',
    'homeGuideSub': 'طریقہ کار قدم بہ قدم',
    'homeToolsTitle': 'ٹولز',
    'homeToolsSub': 'سکینر، ترجمہ، سیمولیٹر',
    'homeAskTitle': 'پیٹروناتو سے پوچھیں',
    'homeAskSub': 'AI سے فوری جواب',
    'sbrogliaAsk': 'پوچھیں',
    'sbrogliaAskPatronato': 'پیٹروناتو سے پوچھیں',
    'sbrogliaSubtitle': 'کوئی بھی سوال پوچھیں —\nفوری اور درست جواب۔',
    'sbrogliaWhoAreYou': 'آپ کون ہیں؟',
    'sbrogliaWhoAreYouSub': '100% ذاتی جوابات کے لیے\nاپنا پروفائل منتخب کریں',
    'sbrogliaInputHint': 'Sbroglia.AI سے پوچھیں...',
    'uploadIsee': 'اپنا ISEE اپلوڈ کریں',
    'uploadIseeSub': 'AI آپ کے ISEE سرٹیفکیٹ (تصویر یا PDF) کو پڑھتا ہے اور خاندان کا ڈیٹا خود بخود بھر دیتا ہے۔',
    'uploadIseeBtn': 'ISEE اپلوڈ (تصویر یا PDF)',
    'continueWithoutIsee': 'میرے پاس ISEE نہیں ہے — بغیر جاری رکھیں',
    'discoverMyRights': 'میرے حقوق جانیں',
    'myRightsTitle': 'آپ کے حقوق',
    'readingIsee': 'ISEE پڑھ رہا ہوں...',
    'iseeRead': 'ISEE پڑھا گیا۔ ڈیٹا بھر دیا۔',
    'fillAllAnswers': 'جوابات مکمل کریں',
    'back': 'پیچھے',
    'next': 'آگے',
    'qSex': 'جنس',
    'qSexMale': 'مرد',
    'qSexFemale': 'عورت',
    'qCitizenship': 'شہریت',
    'qCitIT': 'اطالوی',
    'qCitUE': 'یورپی یونین',
    'qCitExtraUE': 'غیر یورپی',
    'qYearsInItaly': 'آپ اٹلی میں کتنے سال سے ہیں؟',
    'qWorkStatus': 'ملازمت کی صورت حال',
    'qEmployee': 'ملازم',
    'qSelfEmployed': 'خود روزگار',
    'qUnemployed': 'بے روزگار',
    'qRetired': 'ریٹائرڈ',
    'qStudent': 'طالب علم',
    'qIncome': 'سالانہ ذاتی مجموعی آمدنی',
    'qIncomeHelp': '(ISEE سے مختلف)',
    'qRenting': 'کیا آپ کرائے پر رہتے ہیں؟',
    'qYes': 'ہاں',
    'qNo': 'نہیں',
    'qMerit100': 'کیا آپ نے 100/100 نمبر لیے ہیں؟',
    'qDisability': 'کیا آپ کی کوئی تسلیم شدہ معذوری ہے؟',
    'loading': 'لوڈ ہو رہا ہے...',
    'error': 'خرابی',
    'retry': 'دوبارہ کوشش',
    'close': 'بند کریں',
    'search': 'تلاش',
    'cancel': 'منسوخ',
    'save': 'محفوظ',
    'confirm': 'تصدیق',
    'newBonusNotifTitle': 'نیا بونس دستیاب',
    'docExpiryNotifTitle': 'دستاویز کی میعاد ختم ہو رہی ہے',
  };

  // ═══════════════════════════════════════════════════════════════════
  // HINDI — Indian immigrants
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _hi = {
    'appName': 'मेरा पैट्रोनाटो',
    'appTagline': 'इतालवी नौकरशाही आपकी जेब में',
    'chooseLanguage': 'अपनी भाषा चुनें',
    'chooseLanguageSubtitle': 'आप इसे सेटिंग्स से कभी भी बदल सकते हैं',
    'continueBtn': 'जारी रखें',
    'welcome': 'स्वागत है',
    'getStarted': 'शुरू करें',
    'navHome': 'होम',
    'navBonuses': 'बोनस',
    'navAsk': 'पूछें',
    'navProfile': 'प्रोफ़ाइल',
    'homeHeaderTitle': 'मेरा पैट्रोनाटो',
    'homeHeaderSubtitle': 'इतालवी नौकरशाही आपकी जेब में',
    'homeDiscoverRights': 'अपने अधिकार जानें',
    'homeDiscoverRightsSub': 'ISEE अपलोड करें और जानें कौन से बोनस मिल सकते हैं',
    'homeGuideTitle': 'गाइड और दस्तावेज़',
    'homeGuideSub': 'प्रक्रियाएं चरण-दर-चरण',
    'homeToolsTitle': 'उपकरण',
    'homeToolsSub': 'स्कैनर, अनुवादक, सिम्युलेटर',
    'homeAskTitle': 'पैट्रोनाटो से पूछें',
    'homeAskSub': 'AI से तुरंत उत्तर',
    'sbrogliaAsk': 'पूछें',
    'sbrogliaAskPatronato': 'पैट्रोनाटो से पूछें',
    'sbrogliaSubtitle': 'कोई भी सवाल पूछें —\nतुरंत और सटीक उत्तर।',
    'sbrogliaWhoAreYou': 'आप कौन हैं?',
    'sbrogliaWhoAreYouSub': '100% व्यक्तिगत उत्तर के लिए\nअपना प्रोफ़ाइल चुनें',
    'sbrogliaInputHint': 'Sbroglia.AI से पूछें...',
    'uploadIsee': 'अपना ISEE अपलोड करें',
    'uploadIseeSub': 'AI आपके ISEE प्रमाणपत्र (फोटो या PDF) को पढ़ता है और परिवार का डेटा अपने आप भर देता है।',
    'uploadIseeBtn': 'ISEE अपलोड (फोटो या PDF)',
    'continueWithoutIsee': 'मेरे पास ISEE नहीं है — बिना जारी रखें',
    'discoverMyRights': 'मेरे अधिकार खोजें',
    'myRightsTitle': 'आपके अधिकार',
    'readingIsee': 'ISEE पढ़ रहा हूँ...',
    'iseeRead': 'ISEE पढ़ा गया। डेटा भर दिया।',
    'fillAllAnswers': 'उत्तर पूरे करें',
    'back': 'पीछे',
    'next': 'आगे',
    'qSex': 'लिंग',
    'qSexMale': 'पुरुष',
    'qSexFemale': 'महिला',
    'qCitizenship': 'नागरिकता',
    'qCitIT': 'इतालवी',
    'qCitUE': 'EU',
    'qCitExtraUE': 'गैर-EU',
    'qYearsInItaly': 'आप इटली में कितने साल से हैं?',
    'qWorkStatus': 'काम की स्थिति',
    'qEmployee': 'कर्मचारी',
    'qSelfEmployed': 'स्व-नियोजित',
    'qUnemployed': 'बेरोज़गार',
    'qRetired': 'सेवानिवृत्त',
    'qStudent': 'छात्र',
    'qIncome': 'वार्षिक सकल व्यक्तिगत आय',
    'qIncomeHelp': '(ISEE से अलग)',
    'qRenting': 'क्या आप किराए पर रहते हैं?',
    'qYes': 'हाँ',
    'qNo': 'नहीं',
    'qMerit100': 'क्या आपने 100/100 अंक पाए?',
    'qDisability': 'क्या आपकी कोई मान्यता प्राप्त विकलांगता है?',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'retry': 'फिर से कोशिश करें',
    'close': 'बंद',
    'search': 'खोज',
    'cancel': 'रद्द',
    'save': 'सहेजें',
    'confirm': 'पुष्टि',
    'newBonusNotifTitle': 'नया बोनस उपलब्ध',
    'docExpiryNotifTitle': 'दस्तावेज़ जल्द समाप्त',
  };

  // ═══════════════════════════════════════════════════════════════════
  // ROMANIAN
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _ro = {
    'appName': 'Patronatul Meu',
    'appTagline': 'Birocrația italiană în buzunar',
    'chooseLanguage': 'Alege limba ta',
    'chooseLanguageSubtitle': 'O poți schimba oricând din setări',
    'continueBtn': 'Continuă',
    'welcome': 'Bine ai venit',
    'getStarted': 'Începe',
    'navHome': 'Acasă',
    'navBonuses': 'Bonusuri',
    'navAsk': 'Întreabă',
    'navProfile': 'Profil',
    'homeHeaderTitle': 'Patronatul Meu',
    'homeHeaderSubtitle': 'Birocrația italiană în buzunar',
    'homeDiscoverRights': 'Descoperă-ți drepturile',
    'homeDiscoverRightsSub': 'Încarcă ISEE și află la ce bonusuri ai dreptul',
    'homeGuideTitle': 'Ghiduri și documente',
    'homeGuideSub': 'Proceduri explicate pas cu pas',
    'homeToolsTitle': 'Instrumente',
    'homeToolsSub': 'Scanner, traducător, simulator',
    'homeAskTitle': 'Întreabă Patronatul',
    'homeAskSub': 'Răspuns instant de la AI',
    'sbrogliaAsk': 'ÎNTREABĂ',
    'sbrogliaAskPatronato': 'Întreabă Patronatul',
    'sbrogliaSubtitle': 'Pune orice întrebare — răspuns\ninstant și precis.',
    'sbrogliaWhoAreYou': 'Cine ești?',
    'sbrogliaWhoAreYouSub': 'Alege-ți profilul pentru răspunsuri\n100% personalizate',
    'sbrogliaInputHint': 'Întreabă Sbroglia.AI...',
    'uploadIsee': 'Încarcă ISEE-ul tău',
    'uploadIseeSub': 'AI citește certificatul ISEE (foto sau PDF) și completează automat datele familiei.',
    'uploadIseeBtn': 'ÎNCARCĂ ISEE (foto sau PDF)',
    'continueWithoutIsee': 'Nu am ISEE — continuă fără',
    'discoverMyRights': 'DESCOPERĂ DREPTURILE MELE',
    'myRightsTitle': 'Drepturile tale',
    'readingIsee': 'Citesc ISEE...',
    'iseeRead': 'ISEE citit. Datele completate.',
    'fillAllAnswers': 'Completează răspunsurile',
    'back': 'Înapoi',
    'next': 'Înainte',
    'qSex': 'Sex',
    'qSexMale': 'Bărbat',
    'qSexFemale': 'Femeie',
    'qCitizenship': 'Cetățenie',
    'qCitIT': 'Italiană',
    'qCitUE': 'UE',
    'qCitExtraUE': 'Non-UE',
    'qYearsInItaly': 'De câți ani trăiești în Italia?',
    'qWorkStatus': 'Situație profesională',
    'qEmployee': 'Angajat',
    'qSelfEmployed': 'Liber-profesionist',
    'qUnemployed': 'Șomer',
    'qRetired': 'Pensionar',
    'qStudent': 'Student',
    'qIncome': 'Venit personal anual BRUT',
    'qIncomeHelp': '(diferit de ISEE)',
    'qRenting': 'Stai cu chirie?',
    'qYes': 'Da',
    'qNo': 'Nu',
    'qMerit100': 'Ai obținut 100/100 la bac?',
    'qDisability': 'Ai o dizabilitate recunoscută?',
    'loading': 'Se încarcă...',
    'error': 'Eroare',
    'retry': 'Reîncearcă',
    'close': 'Închide',
    'search': 'Caută',
    'cancel': 'Anulează',
    'save': 'Salvează',
    'confirm': 'Confirmă',
    'newBonusNotifTitle': 'Bonus nou disponibil',
    'docExpiryNotifTitle': 'Document pe cale să expire',
  };

  // ═══════════════════════════════════════════════════════════════════
  // FRENCH
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _fr = {
    'appName': 'Mon Patronato',
    'appTagline': 'La bureaucratie italienne dans votre poche',
    'chooseLanguage': 'Choisissez votre langue',
    'chooseLanguageSubtitle': 'Vous pouvez la changer à tout moment dans les paramètres',
    'continueBtn': 'Continuer',
    'welcome': 'Bienvenue',
    'getStarted': 'Commencer',
    'navHome': 'Accueil',
    'navBonuses': 'Aides',
    'navAsk': 'Demander',
    'navProfile': 'Profil',
    'homeHeaderTitle': 'Mon Patronato',
    'homeHeaderSubtitle': 'La bureaucratie italienne dans votre poche',
    'homeDiscoverRights': 'Découvrez vos droits',
    'homeDiscoverRightsSub': 'Téléversez ISEE et découvrez les aides auxquelles vous avez droit',
    'homeGuideTitle': 'Guides et documents',
    'homeGuideSub': 'Procédures expliquées étape par étape',
    'homeToolsTitle': 'Outils',
    'homeToolsSub': 'Scanner, traducteur, simulateur',
    'homeAskTitle': 'Demandez au Patronato',
    'homeAskSub': 'Réponse instantanée de l\'IA',
    'sbrogliaAsk': 'DEMANDER',
    'sbrogliaAskPatronato': 'Demandez au Patronato',
    'sbrogliaSubtitle': 'Posez une question — réponse\ninstantanée et précise.',
    'sbrogliaWhoAreYou': 'Qui êtes-vous ?',
    'sbrogliaWhoAreYouSub': 'Choisissez votre profil pour\ndes réponses 100% personnalisées',
    'sbrogliaInputHint': 'Demandez à Sbroglia.AI...',
    'uploadIsee': 'Téléversez votre ISEE',
    'uploadIseeSub': 'L\'IA lit votre attestation ISEE (photo ou PDF) et remplit automatiquement les données du foyer.',
    'uploadIseeBtn': 'TÉLÉVERSER ISEE (photo ou PDF)',
    'continueWithoutIsee': 'Je n\'ai pas d\'ISEE — continuer sans',
    'discoverMyRights': 'DÉCOUVRIR MES DROITS',
    'myRightsTitle': 'Vos droits',
    'readingIsee': 'Lecture ISEE...',
    'iseeRead': 'ISEE lu. Données remplies.',
    'fillAllAnswers': 'Complétez les réponses',
    'back': 'Retour',
    'next': 'Suivant',
    'qSex': 'Sexe',
    'qSexMale': 'Homme',
    'qSexFemale': 'Femme',
    'qCitizenship': 'Nationalité',
    'qCitIT': 'Italienne',
    'qCitUE': 'UE',
    'qCitExtraUE': 'Hors UE',
    'qYearsInItaly': 'Depuis combien d\'années vivez-vous en Italie ?',
    'qWorkStatus': 'Situation professionnelle',
    'qEmployee': 'Salarié',
    'qSelfEmployed': 'Indépendant',
    'qUnemployed': 'Sans emploi',
    'qRetired': 'Retraité',
    'qStudent': 'Étudiant',
    'qIncome': 'Revenu personnel annuel BRUT',
    'qIncomeHelp': '(différent de l\'ISEE)',
    'qRenting': 'Êtes-vous locataire ?',
    'qYes': 'Oui',
    'qNo': 'Non',
    'qMerit100': 'Avez-vous eu 100/100 au bac ?',
    'qDisability': 'Avez-vous un handicap reconnu ?',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'retry': 'Réessayer',
    'close': 'Fermer',
    'search': 'Rechercher',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'confirm': 'Confirmer',
    'newBonusNotifTitle': 'Nouvelle aide disponible',
    'docExpiryNotifTitle': 'Document bientôt expiré',
  };

  // ═══════════════════════════════════════════════════════════════════
  // SPANISH
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _es = {
    'appName': 'Mi Patronato',
    'appTagline': 'La burocracia italiana en tu bolsillo',
    'chooseLanguage': 'Elige tu idioma',
    'chooseLanguageSubtitle': 'Podrás cambiarlo en cualquier momento en ajustes',
    'continueBtn': 'Continuar',
    'welcome': 'Bienvenido',
    'getStarted': 'Comenzar',
    'navHome': 'Inicio',
    'navBonuses': 'Ayudas',
    'navAsk': 'Preguntar',
    'navProfile': 'Perfil',
    'homeHeaderTitle': 'Mi Patronato',
    'homeHeaderSubtitle': 'La burocracia italiana en tu bolsillo',
    'homeDiscoverRights': 'Descubre tus derechos',
    'homeDiscoverRightsSub': 'Sube ISEE y descubre a qué ayudas tienes derecho',
    'homeGuideTitle': 'Guías y documentos',
    'homeGuideSub': 'Procedimientos explicados paso a paso',
    'homeToolsTitle': 'Herramientas',
    'homeToolsSub': 'Escáner, traductor, simulador',
    'homeAskTitle': 'Pregunta al Patronato',
    'homeAskSub': 'Respuesta instantánea de la IA',
    'sbrogliaAsk': 'PREGUNTAR',
    'sbrogliaAskPatronato': 'Pregunta al Patronato',
    'sbrogliaSubtitle': 'Haz cualquier pregunta —\nrespuesta instantánea y precisa.',
    'sbrogliaWhoAreYou': '¿Quién eres?',
    'sbrogliaWhoAreYouSub': 'Elige tu perfil para respuestas\n100% personalizadas',
    'sbrogliaInputHint': 'Pregunta a Sbroglia.AI...',
    'uploadIsee': 'Sube tu ISEE',
    'uploadIseeSub': 'La IA lee tu certificado ISEE (foto o PDF) y rellena automáticamente los datos familiares.',
    'uploadIseeBtn': 'SUBIR ISEE (foto o PDF)',
    'continueWithoutIsee': 'No tengo ISEE — continuar sin',
    'discoverMyRights': 'DESCUBRIR MIS DERECHOS',
    'myRightsTitle': 'Tus derechos',
    'readingIsee': 'Leyendo ISEE...',
    'iseeRead': 'ISEE leído. Datos rellenados.',
    'fillAllAnswers': 'Completa las respuestas',
    'back': 'Atrás',
    'next': 'Siguiente',
    'qSex': 'Sexo',
    'qSexMale': 'Hombre',
    'qSexFemale': 'Mujer',
    'qCitizenship': 'Nacionalidad',
    'qCitIT': 'Italiana',
    'qCitUE': 'UE',
    'qCitExtraUE': 'Extra-UE',
    'qYearsInItaly': '¿Cuántos años llevas en Italia?',
    'qWorkStatus': 'Situación laboral',
    'qEmployee': 'Empleado',
    'qSelfEmployed': 'Autónomo',
    'qUnemployed': 'Desempleado',
    'qRetired': 'Jubilado',
    'qStudent': 'Estudiante',
    'qIncome': 'Ingreso personal anual BRUTO',
    'qIncomeHelp': '(diferente del ISEE)',
    'qRenting': '¿Vives de alquiler?',
    'qYes': 'Sí',
    'qNo': 'No',
    'qMerit100': '¿Sacaste 100/100 en la selectividad?',
    'qDisability': '¿Tienes una discapacidad reconocida?',
    'loading': 'Cargando...',
    'error': 'Error',
    'retry': 'Reintentar',
    'close': 'Cerrar',
    'search': 'Buscar',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'confirm': 'Confirmar',
    'newBonusNotifTitle': 'Nueva ayuda disponible',
    'docExpiryNotifTitle': 'Documento a punto de expirar',
  };

  // ═══════════════════════════════════════════════════════════════════
  // ALBANIAN
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _sq = {
    'appName': 'Patronatoja Ime',
    'appTagline': 'Burokracia italiane në xhepin tënd',
    'chooseLanguage': 'Zgjidh gjuhën tënde',
    'chooseLanguageSubtitle': 'Mund ta ndryshosh në çdo kohë nga cilësimet',
    'continueBtn': 'Vazhdo',
    'welcome': 'Mirë se vini',
    'getStarted': 'Fillo',
    'navHome': 'Kreu',
    'navBonuses': 'Bonuset',
    'navAsk': 'Pyet',
    'navProfile': 'Profili',
    'homeHeaderTitle': 'Patronatoja Ime',
    'homeHeaderSubtitle': 'Burokracia italiane në xhepin tënd',
    'homeDiscoverRights': 'Zbulo të drejtat tua',
    'homeDiscoverRightsSub': 'Ngarko ISEE dhe zbulo bonuset që të takojnë',
    'homeGuideTitle': 'Udhëzues dhe dokumente',
    'homeGuideSub': 'Procedura të shpjeguara hap pas hapi',
    'homeToolsTitle': 'Mjetet',
    'homeToolsSub': 'Skaneri, përkthyesi, simuluesi',
    'homeAskTitle': 'Pyet Patronatin',
    'homeAskSub': 'Përgjigje e menjëhershme nga AI',
    'sbrogliaAsk': 'PYET',
    'sbrogliaAskPatronato': 'Pyet Patronatin',
    'sbrogliaSubtitle': 'Bëj çdo pyetje — përgjigje\ne menjëhershme dhe e saktë.',
    'sbrogliaWhoAreYou': 'Kush je?',
    'sbrogliaWhoAreYouSub': 'Zgjidh profilin tënd për përgjigje\n100% të personalizuara',
    'sbrogliaInputHint': 'Pyet Sbroglia.AI...',
    'uploadIsee': 'Ngarko ISEE-në tënde',
    'uploadIseeSub': 'AI lexon certifikatën ISEE (foto ose PDF) dhe plotëson automatikisht të dhënat e familjes.',
    'uploadIseeBtn': 'NGARKO ISEE (foto ose PDF)',
    'continueWithoutIsee': 'Nuk kam ISEE — vazhdo pa të',
    'discoverMyRights': 'ZBULO TË DREJTAT E MIA',
    'myRightsTitle': 'Të drejtat tua',
    'readingIsee': 'Duke lexuar ISEE...',
    'iseeRead': 'ISEE u lexua. Të dhënat u plotësuan.',
    'fillAllAnswers': 'Plotëso përgjigjet',
    'back': 'Prapa',
    'next': 'Para',
    'qSex': 'Gjinia',
    'qSexMale': 'Burrë',
    'qSexFemale': 'Grua',
    'qCitizenship': 'Shtetësia',
    'qCitIT': 'Italiane',
    'qCitUE': 'BE',
    'qCitExtraUE': 'Jo-BE',
    'qYearsInItaly': 'Sa vjet ke jetuar në Itali?',
    'qWorkStatus': 'Situata e punës',
    'qEmployee': 'I punësuar',
    'qSelfEmployed': 'I vetëpunësuar',
    'qUnemployed': 'I papunë',
    'qRetired': 'I pensionuar',
    'qStudent': 'Student',
    'qIncome': 'Të ardhurat personale vjetore BRUTO',
    'qIncomeHelp': '(ndryshe nga ISEE)',
    'qRenting': 'Jeton me qira?',
    'qYes': 'Po',
    'qNo': 'Jo',
    'qMerit100': 'Ke marrë 100/100 në maturë?',
    'qDisability': 'Ke një aftësi të kufizuar të njohur?',
    'loading': 'Duke ngarkuar...',
    'error': 'Gabim',
    'retry': 'Riprovo',
    'close': 'Mbyll',
    'search': 'Kërko',
    'cancel': 'Anulo',
    'save': 'Ruaj',
    'confirm': 'Konfirmo',
    'newBonusNotifTitle': 'Bonus i ri në dispozicion',
    'docExpiryNotifTitle': 'Dokument që do të skadojë',
  };

  // ═══════════════════════════════════════════════════════════════════
  // CHINESE (simplified)
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _zh = {
    'appName': '我的帮助中心',
    'appTagline': '意大利官僚体系尽在掌握',
    'chooseLanguage': '选择您的语言',
    'chooseLanguageSubtitle': '您可以随时在设置中更改',
    'continueBtn': '继续',
    'welcome': '欢迎',
    'getStarted': '开始',
    'navHome': '首页',
    'navBonuses': '福利',
    'navAsk': '询问',
    'navProfile': '个人资料',
    'homeHeaderTitle': '我的帮助中心',
    'homeHeaderSubtitle': '意大利官僚体系尽在掌握',
    'homeDiscoverRights': '了解您的权利',
    'homeDiscoverRightsSub': '上传 ISEE,发现您可以申请的福利',
    'homeGuideTitle': '指南和文档',
    'homeGuideSub': '逐步说明程序',
    'homeToolsTitle': '工具',
    'homeToolsSub': '扫描仪、翻译、模拟器',
    'homeAskTitle': '询问帮助中心',
    'homeAskSub': 'AI 即时回复',
    'sbrogliaAsk': '询问',
    'sbrogliaAskPatronato': '询问帮助中心',
    'sbrogliaSubtitle': '询问任何问题 — 获得\n即时且准确的回复。',
    'sbrogliaWhoAreYou': '您是谁?',
    'sbrogliaWhoAreYouSub': '选择您的个人资料以获得\n100% 个性化回复',
    'sbrogliaInputHint': '询问 Sbroglia.AI...',
    'uploadIsee': '上传您的 ISEE',
    'uploadIseeSub': 'AI 读取您的 ISEE 证书(照片或 PDF)并自动填写家庭数据。',
    'uploadIseeBtn': '上传 ISEE (照片或 PDF)',
    'continueWithoutIsee': '我没有 ISEE — 继续',
    'discoverMyRights': '发现我的权利',
    'myRightsTitle': '您的权利',
    'readingIsee': '正在读取 ISEE...',
    'iseeRead': 'ISEE 已读取。数据已填写。',
    'fillAllAnswers': '完成回答',
    'back': '返回',
    'next': '下一个',
    'qSex': '性别',
    'qSexMale': '男',
    'qSexFemale': '女',
    'qCitizenship': '国籍',
    'qCitIT': '意大利',
    'qCitUE': '欧盟',
    'qCitExtraUE': '非欧盟',
    'qYearsInItaly': '您在意大利住了多少年?',
    'qWorkStatus': '工作状态',
    'qEmployee': '受雇者',
    'qSelfEmployed': '自雇',
    'qUnemployed': '失业',
    'qRetired': '退休',
    'qStudent': '学生',
    'qIncome': '年度总个人收入',
    'qIncomeHelp': '(与 ISEE 不同)',
    'qRenting': '您租房吗?',
    'qYes': '是',
    'qNo': '否',
    'qMerit100': '您是否获得了 100/100 的毕业成绩?',
    'qDisability': '您有被认可的残疾吗?',
    'loading': '加载中...',
    'error': '错误',
    'retry': '重试',
    'close': '关闭',
    'search': '搜索',
    'cancel': '取消',
    'save': '保存',
    'confirm': '确认',
    'newBonusNotifTitle': '有新福利',
    'docExpiryNotifTitle': '文件即将到期',
  };

  // ═══════════════════════════════════════════════════════════════════
  // BENGALI
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _bn = {
    'appName': 'আমার প্যাট্রোনাটো',
    'appTagline': 'ইতালীয় আমলাতন্ত্র আপনার পকেটে',
    'chooseLanguage': 'আপনার ভাষা নির্বাচন করুন',
    'chooseLanguageSubtitle': 'আপনি সেটিংস থেকে যেকোনো সময় পরিবর্তন করতে পারেন',
    'continueBtn': 'চালিয়ে যান',
    'welcome': 'স্বাগতম',
    'getStarted': 'শুরু করুন',
    'navHome': 'হোম',
    'navBonuses': 'বোনাস',
    'navAsk': 'জিজ্ঞাসা',
    'navProfile': 'প্রোফাইল',
    'homeHeaderTitle': 'আমার প্যাট্রোনাটো',
    'homeHeaderSubtitle': 'ইতালীয় আমলাতন্ত্র আপনার পকেটে',
    'homeDiscoverRights': 'আপনার অধিকার জানুন',
    'homeDiscoverRightsSub': 'ISEE আপলোড করে জানুন আপনি কোন বোনাস পাবেন',
    'homeGuideTitle': 'গাইড এবং নথি',
    'homeGuideSub': 'ধাপে ধাপে পদ্ধতি',
    'homeToolsTitle': 'সরঞ্জাম',
    'homeToolsSub': 'স্ক্যানার, অনুবাদক, সিমুলেটর',
    'homeAskTitle': 'প্যাট্রোনাটোকে জিজ্ঞাসা করুন',
    'homeAskSub': 'AI থেকে তাত্ক্ষণিক উত্তর',
    'sbrogliaAsk': 'জিজ্ঞাসা',
    'sbrogliaAskPatronato': 'প্যাট্রোনাটোকে জিজ্ঞাসা',
    'sbrogliaSubtitle': 'যেকোনো প্রশ্ন করুন —\nতাত্ক্ষণিক এবং সঠিক উত্তর।',
    'sbrogliaWhoAreYou': 'আপনি কে?',
    'sbrogliaWhoAreYouSub': '100% ব্যক্তিগত উত্তরের জন্য\nআপনার প্রোফাইল নির্বাচন করুন',
    'sbrogliaInputHint': 'Sbroglia.AI কে জিজ্ঞাসা...',
    'uploadIsee': 'আপনার ISEE আপলোড করুন',
    'uploadIseeSub': 'AI আপনার ISEE সার্টিফিকেট (ছবি বা PDF) পড়ে এবং পরিবারের তথ্য স্বয়ংক্রিয়ভাবে পূরণ করে।',
    'uploadIseeBtn': 'ISEE আপলোড (ছবি বা PDF)',
    'continueWithoutIsee': 'আমার ISEE নেই — এগিয়ে যান',
    'discoverMyRights': 'আমার অধিকার জানুন',
    'myRightsTitle': 'আপনার অধিকার',
    'readingIsee': 'ISEE পড়ছি...',
    'iseeRead': 'ISEE পড়া হয়েছে। তথ্য পূরণ হয়েছে।',
    'fillAllAnswers': 'উত্তরগুলো সম্পূর্ণ করুন',
    'back': 'পিছনে',
    'next': 'পরবর্তী',
    'qSex': 'লিঙ্গ',
    'qSexMale': 'পুরুষ',
    'qSexFemale': 'মহিলা',
    'qCitizenship': 'নাগরিকত্ব',
    'qCitIT': 'ইতালীয়',
    'qCitUE': 'EU',
    'qCitExtraUE': 'নন-EU',
    'qYearsInItaly': 'আপনি কত বছর ইতালিতে আছেন?',
    'qWorkStatus': 'কাজের অবস্থা',
    'qEmployee': 'কর্মচারী',
    'qSelfEmployed': 'স্ব-নিযুক্ত',
    'qUnemployed': 'বেকার',
    'qRetired': 'অবসরপ্রাপ্ত',
    'qStudent': 'ছাত্র',
    'qIncome': 'বার্ষিক মোট ব্যক্তিগত আয়',
    'qIncomeHelp': '(ISEE থেকে আলাদা)',
    'qRenting': 'আপনি ভাড়ায় থাকেন?',
    'qYes': 'হ্যাঁ',
    'qNo': 'না',
    'qMerit100': 'আপনি কি 100/100 পেয়েছেন?',
    'qDisability': 'আপনার কি স্বীকৃত প্রতিবন্ধিতা আছে?',
    'loading': 'লোড হচ্ছে...',
    'error': 'ত্রুটি',
    'retry': 'আবার চেষ্টা',
    'close': 'বন্ধ',
    'search': 'খুঁজুন',
    'cancel': 'বাতিল',
    'save': 'সংরক্ষণ',
    'confirm': 'নিশ্চিত',
    'newBonusNotifTitle': 'নতুন বোনাস',
    'docExpiryNotifTitle': 'নথি শীঘ্রই শেষ হচ্ছে',
  };

  // ═══════════════════════════════════════════════════════════════════
  // UKRAINIAN
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _uk = {
    'appName': 'Мій Патронат',
    'appTagline': 'Італійська бюрократія у вашій кишені',
    'chooseLanguage': 'Виберіть вашу мову',
    'chooseLanguageSubtitle': 'Ви можете змінити її будь-коли в налаштуваннях',
    'continueBtn': 'Продовжити',
    'welcome': 'Ласкаво просимо',
    'getStarted': 'Почати',
    'navHome': 'Головна',
    'navBonuses': 'Бонуси',
    'navAsk': 'Запитати',
    'navProfile': 'Профіль',
    'homeHeaderTitle': 'Мій Патронат',
    'homeHeaderSubtitle': 'Італійська бюрократія у вашій кишені',
    'homeDiscoverRights': 'Дізнайтеся свої права',
    'homeDiscoverRightsSub': 'Завантажте ISEE і дізнайтеся, які бонуси вам належать',
    'homeGuideTitle': 'Гіди та документи',
    'homeGuideSub': 'Процедури покроково',
    'homeToolsTitle': 'Інструменти',
    'homeToolsSub': 'Сканер, перекладач, симулятор',
    'homeAskTitle': 'Запитайте Патронат',
    'homeAskSub': 'Миттєва відповідь від AI',
    'sbrogliaAsk': 'ЗАПИТАТИ',
    'sbrogliaAskPatronato': 'Запитайте Патронат',
    'sbrogliaSubtitle': 'Задайте будь-яке питання —\nмиттєва та точна відповідь.',
    'sbrogliaWhoAreYou': 'Хто ви?',
    'sbrogliaWhoAreYouSub': 'Виберіть профіль для\n100% персоналізованих відповідей',
    'sbrogliaInputHint': 'Запитайте Sbroglia.AI...',
    'uploadIsee': 'Завантажте ваш ISEE',
    'uploadIseeSub': 'AI читає сертифікат ISEE (фото або PDF) і автоматично заповнює дані сім\'ї.',
    'uploadIseeBtn': 'ЗАВАНТАЖИТИ ISEE (фото або PDF)',
    'continueWithoutIsee': 'У мене немає ISEE — продовжити без',
    'discoverMyRights': 'ДІЗНАТИСЯ МОЇ ПРАВА',
    'myRightsTitle': 'Ваші права',
    'readingIsee': 'Читаю ISEE...',
    'iseeRead': 'ISEE прочитано. Дані заповнено.',
    'fillAllAnswers': 'Завершіть відповіді',
    'back': 'Назад',
    'next': 'Далі',
    'qSex': 'Стать',
    'qSexMale': 'Чоловік',
    'qSexFemale': 'Жінка',
    'qCitizenship': 'Громадянство',
    'qCitIT': 'Італійське',
    'qCitUE': 'ЄС',
    'qCitExtraUE': 'Не-ЄС',
    'qYearsInItaly': 'Скільки років ви живете в Італії?',
    'qWorkStatus': 'Робочий статус',
    'qEmployee': 'Працівник',
    'qSelfEmployed': 'Самозайнятий',
    'qUnemployed': 'Безробітний',
    'qRetired': 'Пенсіонер',
    'qStudent': 'Студент',
    'qIncome': 'Річний валовий особистий дохід',
    'qIncomeHelp': '(відрізняється від ISEE)',
    'qRenting': 'Ви орендуєте житло?',
    'qYes': 'Так',
    'qNo': 'Ні',
    'qMerit100': 'Ви отримали 100/100 на іспиті?',
    'qDisability': 'У вас є визнана інвалідність?',
    'loading': 'Завантаження...',
    'error': 'Помилка',
    'retry': 'Спробувати знову',
    'close': 'Закрити',
    'search': 'Пошук',
    'cancel': 'Скасувати',
    'save': 'Зберегти',
    'confirm': 'Підтвердити',
    'newBonusNotifTitle': 'Новий бонус',
    'docExpiryNotifTitle': 'Документ скоро закінчується',
  };

  // ═══════════════════════════════════════════════════════════════════
  // RUSSIAN
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _ru = {
    'appName': 'Мой Патронат',
    'appTagline': 'Итальянская бюрократия в вашем кармане',
    'chooseLanguage': 'Выберите ваш язык',
    'chooseLanguageSubtitle': 'Вы можете изменить его в любое время в настройках',
    'continueBtn': 'Продолжить',
    'welcome': 'Добро пожаловать',
    'getStarted': 'Начать',
    'navHome': 'Главная',
    'navBonuses': 'Бонусы',
    'navAsk': 'Спросить',
    'navProfile': 'Профиль',
    'homeHeaderTitle': 'Мой Патронат',
    'homeHeaderSubtitle': 'Итальянская бюрократия в вашем кармане',
    'homeDiscoverRights': 'Узнайте свои права',
    'homeDiscoverRightsSub': 'Загрузите ISEE и узнайте, на какие бонусы вы имеете право',
    'homeGuideTitle': 'Руководства и документы',
    'homeGuideSub': 'Процедуры шаг за шагом',
    'homeToolsTitle': 'Инструменты',
    'homeToolsSub': 'Сканер, переводчик, симулятор',
    'homeAskTitle': 'Спросить Патронат',
    'homeAskSub': 'Мгновенный ответ от AI',
    'sbrogliaAsk': 'СПРОСИТЬ',
    'sbrogliaAskPatronato': 'Спросить Патронат',
    'sbrogliaSubtitle': 'Задайте любой вопрос —\nмгновенный и точный ответ.',
    'sbrogliaWhoAreYou': 'Кто вы?',
    'sbrogliaWhoAreYouSub': 'Выберите свой профиль для\n100% персонализированных ответов',
    'sbrogliaInputHint': 'Спросите Sbroglia.AI...',
    'uploadIsee': 'Загрузите ваш ISEE',
    'uploadIseeSub': 'AI читает сертификат ISEE (фото или PDF) и автоматически заполняет данные семьи.',
    'uploadIseeBtn': 'ЗАГРУЗИТЬ ISEE (фото или PDF)',
    'continueWithoutIsee': 'У меня нет ISEE — продолжить без него',
    'discoverMyRights': 'УЗНАТЬ МОИ ПРАВА',
    'myRightsTitle': 'Ваши права',
    'readingIsee': 'Читаю ISEE...',
    'iseeRead': 'ISEE прочитан. Данные заполнены.',
    'fillAllAnswers': 'Завершите ответы',
    'back': 'Назад',
    'next': 'Далее',
    'qSex': 'Пол',
    'qSexMale': 'Мужчина',
    'qSexFemale': 'Женщина',
    'qCitizenship': 'Гражданство',
    'qCitIT': 'Итальянское',
    'qCitUE': 'ЕС',
    'qCitExtraUE': 'Не-ЕС',
    'qYearsInItaly': 'Сколько лет вы живёте в Италии?',
    'qWorkStatus': 'Статус занятости',
    'qEmployee': 'Работник',
    'qSelfEmployed': 'Самозанятый',
    'qUnemployed': 'Безработный',
    'qRetired': 'Пенсионер',
    'qStudent': 'Студент',
    'qIncome': 'Годовой валовой личный доход',
    'qIncomeHelp': '(отличается от ISEE)',
    'qRenting': 'Вы снимаете жильё?',
    'qYes': 'Да',
    'qNo': 'Нет',
    'qMerit100': 'Вы получили 100/100 на экзамене?',
    'qDisability': 'У вас есть признанная инвалидность?',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'retry': 'Повторить',
    'close': 'Закрыть',
    'search': 'Поиск',
    'cancel': 'Отмена',
    'save': 'Сохранить',
    'confirm': 'Подтвердить',
    'newBonusNotifTitle': 'Новый бонус',
    'docExpiryNotifTitle': 'Срок действия документа истекает',
  };

  // ═══════════════════════════════════════════════════════════════════
  // PUNJABI (Gurmukhi script) — Indian Punjabi immigrants
  // ═══════════════════════════════════════════════════════════════════
  static const Map<String, String> _pa = {
    'appName': 'ਮੇਰਾ ਪੈਟਰੋਨਾਟੋ',
    'appTagline': 'ਇਤਾਲਵੀ ਬਿਊਰੋਕ੍ਰੇਸੀ ਤੁਹਾਡੀ ਜੇਬ ਵਿੱਚ',
    'chooseLanguage': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    'chooseLanguageSubtitle': 'ਤੁਸੀਂ ਇਸਨੂੰ ਸੈਟਿੰਗਾਂ ਤੋਂ ਕਿਸੇ ਵੀ ਸਮੇਂ ਬਦਲ ਸਕਦੇ ਹੋ',
    'continueBtn': 'ਜਾਰੀ ਰੱਖੋ',
    'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ',
    'getStarted': 'ਸ਼ੁਰੂ ਕਰੋ',
    'navHome': 'ਮੁੱਖ',
    'navBonuses': 'ਬੋਨਸ',
    'navAsk': 'ਪੁੱਛੋ',
    'navProfile': 'ਪ੍ਰੋਫਾਈਲ',
    'homeHeaderTitle': 'ਮੇਰਾ ਪੈਟਰੋਨਾਟੋ',
    'homeHeaderSubtitle': 'ਇਤਾਲਵੀ ਬਿਊਰੋਕ੍ਰੇਸੀ ਤੁਹਾਡੀ ਜੇਬ ਵਿੱਚ',
    'homeDiscoverRights': 'ਆਪਣੇ ਹੱਕ ਜਾਣੋ',
    'homeDiscoverRightsSub': 'ISEE ਅਪਲੋਡ ਕਰੋ ਅਤੇ ਜਾਣੋ ਤੁਸੀਂ ਕਿਹੜੇ ਬੋਨਸ ਲੈ ਸਕਦੇ ਹੋ',
    'homeGuideTitle': 'ਗਾਈਡ ਅਤੇ ਦਸਤਾਵੇਜ਼',
    'homeGuideSub': 'ਕਦਮ-ਦਰ-ਕਦਮ ਤਰੀਕੇ',
    'homeToolsTitle': 'ਟੂਲ',
    'homeToolsSub': 'ਸਕੈਨਰ, ਅਨੁਵਾਦਕ, ਸਿਮੁਲੇਟਰ',
    'homeAskTitle': 'ਪੈਟਰੋਨਾਟੋ ਨੂੰ ਪੁੱਛੋ',
    'homeAskSub': 'AI ਤੋਂ ਤੁਰੰਤ ਜਵਾਬ',
    'sbrogliaAsk': 'ਪੁੱਛੋ',
    'sbrogliaAskPatronato': 'ਪੈਟਰੋਨਾਟੋ ਨੂੰ ਪੁੱਛੋ',
    'sbrogliaSubtitle': 'ਕੋਈ ਵੀ ਸਵਾਲ ਪੁੱਛੋ —\nਤੁਰੰਤ ਅਤੇ ਸਹੀ ਜਵਾਬ।',
    'sbrogliaWhoAreYou': 'ਤੁਸੀਂ ਕੌਣ ਹੋ?',
    'sbrogliaWhoAreYouSub': '100% ਨਿੱਜੀ ਜਵਾਬਾਂ ਲਈ\nਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਚੁਣੋ',
    'sbrogliaInputHint': 'Sbroglia.AI ਨੂੰ ਪੁੱਛੋ...',
    'uploadIsee': 'ਆਪਣੀ ISEE ਅਪਲੋਡ ਕਰੋ',
    'uploadIseeSub': 'AI ਤੁਹਾਡੀ ISEE ਸਰਟੀਫਿਕੇਟ (ਫੋਟੋ ਜਾਂ PDF) ਨੂੰ ਪੜ੍ਹਦਾ ਹੈ ਅਤੇ ਪਰਿਵਾਰ ਦਾ ਡਾਟਾ ਆਪਣੇ ਆਪ ਭਰ ਦਿੰਦਾ ਹੈ।',
    'uploadIseeBtn': 'ISEE ਅਪਲੋਡ (ਫੋਟੋ ਜਾਂ PDF)',
    'continueWithoutIsee': 'ਮੇਰੇ ਕੋਲ ISEE ਨਹੀਂ — ਬਿਨਾਂ ਜਾਰੀ ਰੱਖੋ',
    'discoverMyRights': 'ਮੇਰੇ ਹੱਕ ਜਾਣੋ',
    'myRightsTitle': 'ਤੁਹਾਡੇ ਹੱਕ',
    'readingIsee': 'ISEE ਪੜ੍ਹ ਰਿਹਾ ਹਾਂ...',
    'iseeRead': 'ISEE ਪੜ੍ਹੀ ਗਈ। ਡਾਟਾ ਭਰਿਆ ਗਿਆ।',
    'fillAllAnswers': 'ਜਵਾਬ ਪੂਰੇ ਕਰੋ',
    'back': 'ਪਿੱਛੇ',
    'next': 'ਅੱਗੇ',
    'qSex': 'ਲਿੰਗ',
    'qSexMale': 'ਮਰਦ',
    'qSexFemale': 'ਔਰਤ',
    'qCitizenship': 'ਨਾਗਰਿਕਤਾ',
    'qCitIT': 'ਇਤਾਲਵੀ',
    'qCitUE': 'EU',
    'qCitExtraUE': 'ਗੈਰ-EU',
    'qYearsInItaly': 'ਤੁਸੀਂ ਇਟਲੀ ਵਿੱਚ ਕਿੰਨੇ ਸਾਲਾਂ ਤੋਂ ਹੋ?',
    'qWorkStatus': 'ਕੰਮ ਦੀ ਸਥਿਤੀ',
    'qEmployee': 'ਕਰਮਚਾਰੀ',
    'qSelfEmployed': 'ਸਵੈ-ਰੋਜ਼ਗਾਰ',
    'qUnemployed': 'ਬੇਰੋਜ਼ਗਾਰ',
    'qRetired': 'ਸੇਵਾਮੁਕਤ',
    'qStudent': 'ਵਿਦਿਆਰਥੀ',
    'qIncome': 'ਸਾਲਾਨਾ ਕੁੱਲ ਨਿੱਜੀ ਆਮਦਨ',
    'qIncomeHelp': '(ISEE ਤੋਂ ਵੱਖਰੀ)',
    'qRenting': 'ਕੀ ਤੁਸੀਂ ਕਿਰਾਏ \'ਤੇ ਰਹਿੰਦੇ ਹੋ?',
    'qYes': 'ਹਾਂ',
    'qNo': 'ਨਹੀਂ',
    'qMerit100': 'ਕੀ ਤੁਸੀਂ 100/100 ਅੰਕ ਲਏ?',
    'qDisability': 'ਕੀ ਤੁਹਾਡੀ ਕੋਈ ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਅਪੰਗਤਾ ਹੈ?',
    'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ...',
    'error': 'ਗਲਤੀ',
    'retry': 'ਮੁੜ ਕੋਸ਼ਿਸ਼',
    'close': 'ਬੰਦ ਕਰੋ',
    'search': 'ਖੋਜ',
    'cancel': 'ਰੱਦ ਕਰੋ',
    'save': 'ਸੰਭਾਲੋ',
    'confirm': 'ਪੁਸ਼ਟੀ',
    'newBonusNotifTitle': 'ਨਵਾਂ ਬੋਨਸ ਉਪਲਬਧ',
    'docExpiryNotifTitle': 'ਦਸਤਾਵੇਜ਼ ਦੀ ਮਿਆਦ ਖਤਮ',
  };
}
